### PR TITLE
Fix typo I've found while doing chap17

### PR DESCRIPTION
**Pull request by hatoo**

### CODE REVIEW

**Comment by nlsandler** [comment]
Thanks for opening this!
Seems like CI is failing because of a problem in my Github workflow - I'll look into it in the next day or two so I can get this merged.

**Comment by nlsandler** [comment]
@hatoo mind if I rebase this to confirm that it fixes the failing checks?

**Comment by hatoo** [comment]
Rebased by rebase button

**Comment by nlsandler** [comment]
Thanks for your contribution!

**Pull request merged**
