### PR TITLE
Complete test suite

### PR DESCRIPTION
**Pull request by nlsandler**
Additional tests and test script
This PR is still a work in progress

### CODE REVIEW

**Comment by nlsandler** [comment]
# Checklist

Ready for review:

- [ ] Chapters you've already reviewed (chapters 1 - 10, previously chapters 2 - 11). I've added new tests, and changed some of the ones you've already reviewed. Because these files have all been renamed, getting git to show a useful diff is a little tricky. To make reviewing them easier, I've uploaded a patch file for changed tests and lists of added and removed tests below.
- [ ] Chapter 11
- [ ] Chapter 12
- [ ] Chapter 13
- [ ] Chapter 14
- [ ] Chapter 15
- [ ] Chapter 16
- [ ] Chapter 17
- [ ] Test runner + supporting files
    - `test_compiler`
    - everything in the `test_framework` directory except `tacky/` and `regalloc.py`
    - `test_properties.json`
    - `generate_expected_results.py`

Not yet ready:

- [ ] Chapter 18
- [ ] Chapter 19
- [ ] Chapter 20
- [ ] Extra-credit tests
- [ ] Test running code for chapters 19 and 20 (`test_framework/tacky/` and `test_framework/regalloc.py`)


# What stuff is where

- C test programs are in the `tests/` subdirectory, organized by chapter. Tests within each chapter are organized by stage.
    - Library/client pairs intended to test ABI compliance are in `libraries/` subdirectories
    - Extra credit tests (in progress) are in `extra_credit/` subdirectories
- The code in `test_framework` uses Python's `unittest`. It dynamically generates a test case for each C program in `tests/`, grouped into per-chapter classes, using a technique borrowed [this blog post](https://eli.thegreenplace.net/2014/04/02/dynamically-generating-python-test-cases).
    - `runner.py` is the main entry point we call from `test_compiler`. It handles arg parsing, figuring out which test classes to generate, and the `--check-setup` option (mentioned in the book's introduction) to make sure system requirements are met. 
    - `basic.py` handles all the testing logic for Chapters 1-18. For most test cases this means compiling a program with the compiler under test, running it, and comparing its output to the expected output in `expected_results.json`. For test cases in `libraries/` subdirectories it compiles one file with the compiler under test and the other with the `gcc` command, links them together, and validates the program's behavior.
    - `parser/` contains a rudimentary assembly code parser, which is used in the tests for Chapter 19 (TACKY optimizations) and 20 (register allocation)
    - `tacky/` and `regalloc.py` contain testing logic for Chapters 19 and 20, respectively
    - `test_tests/` contains unit tests for `test_framework/` itself 
- `generate_expected_results.py` is a utility script to generate `expected_results.json`, which gives the expected return code/output for each test program. Right now I run this script manually; there should probably be CI to run it (or at least complain if `expected_results.json` is out of date).
- `test_properties.json` specifies which programs are extra credit tests, which ones require mathlib (meaning they need to be compiled with the `-lm` switch) and which ones depends on assembly files. (Register allocation tests depend on assembly files that aren't specified here.)

# Diffs for chapters 1 - 10 (which you've already reviewed)

Test cases that were removed, with notes on why: [removed_tests.txt](https://github.com/nlsandler/writing-a-c-compiler-tests/files/12554703/removed_tests.txt)
New test cases: [added_tests.txt](https://github.com/nlsandler/writing-a-c-compiler-tests/files/12554705/added_tests.txt)
Patch file for changed test cases: [chapters.patch](https://github.com/nlsandler/writing-a-c-compiler-tests/files/12554709/chapters.patch)
Just in case you're curious, the janky shell script I used to generate these files (had to rename it so Github would let me upload it) [diffify.sh.txt](https://github.com/nlsandler/writing-a-c-compiler-tests/files/12554710/diffify.sh.txt)


# Notes:

1. Most common changes to existing test cases:
    - changed directory structure (e.g. `chapter3/` --> `tests/chapter_2`)
    - declare functions without parameters as `int f(void)` instead of `int f()`
    - preprocessor directives telling GCC/Clang to suppress warnings. (We need these b/c the tests-for-our-tests in `test_tests/` verify that valid test programs all compile without warning. These directives won't impact readers' compilers because the preprocessor will discard them)
3. Flagging test cases that could use more comments to explain what's being tested is especially useful.
4. You can run these tests against the reference implementation [here](https://github.com/nlsandler/nqcc2)

**Comment by nlsandler** [comment]
Chapter 18 tests are now ready for review!

**Review by stephenrkell — COMMENTED** [review]
The following are some comments on chapters 11 and 12.

# Chapter 11

* `invalid_parse/long_constant_as_var.c`: consider s/where a variable is
required/where an identifier is required/, or qualifying with 'in a
declaration'. (The point being that you very often *can* use a constant
where a variable name is required, just not in the context set up by
this test case.)

* `valid/explicit_casts/sign_extend.c`: consider renaming `sign_extend()` to
`sign_extend_check()` i.e. make clear its behaviour is not that of a
straightforward sign extension function.

* `valid/explicit_casts/truncate.c`: analogous comment as for sign
extension

* `valid/extra_credit/bitwise_long_op.c`: this test seems to return 0 on failure and 1 on
success, which is the opposite of others?

* `extra_credit/switch_long.c'`: another with inverted return value

* `convert_by_assignment.c`: the same naming comment for
`truncate_on_assignment`.

* `convert_function_arguments.c`: perhaps intentional but I noticed that
`c` does not undergo any conversion.

* `long_args.c`: consider adding a comment to refer to `long_args_client.c`

* `long_args_client.c`: refers to chapter 12 but should say chapter 11?

* `long_global_var.c`, `maintain_stack_alignment.c`, `return_long.c`: same comment about
adding a comment :-)

* `return_long_client.c`: same comment about 'chapter12'

* `valid/long_expressions/arithmetic_ops.c`: the many assignments to `a`
are a bit treacherous but OK

* `valid/long_expressions/comparisons.c`: same 'treacherous' comment

* `valid/long_expressions/large_constants.c`: usual naming comment e.g.
for `add_large()`

* `valid/long_expressions/large_constants.c`: another inverted return
value

# Chapter 12

* `valid/explicit_casts/extension.c`: the usual naming comment for
`int_to_ulong()` etc

* `valid/explicit_casts/round_trip_casts.c`: comment wordo 'reduces is
equivalent to' (also "casting to a" maybe should say "casting a to"?)

* `valid/explicit_casts/same_size_conversion.c`: the usual boring naming
comment, that is maybe ignorable after all? It's a consistent pattern at
least. I won't raise it from here on.

*  General comment that's been nagging me for chapters 11 and 12: the
tests would be much more readable if the numbers were not just commented
but were written out arithmetically, i.e. the test cases were
macro-expanded somehow into .c files. But perhaps the test cases are not
primarily to be read.

* `valid/extra_credit/bitwise_unsigned_ops.c`: return value logic
inverted

* `valid/extra_credit/bitwise_unsigned_shift.c`: comment should say
"shifting left". Also the return value logic is inverted.

* `valid/implicit_casts/common_type.c`: typo "convert o a signed long".
Musing on the helper functions that exist to defeat constant folding:
clearly the test would be more readable without them, but also,
presumably we want to test the constant-folding compile-time
implementation of these operations too. If the tests were written
without the helper function, then a reader who worked through the book
systematically and used these tests would end up initially with them
testing a non-constant-folding version of their compiler, i.e. testing
it generates correct code, and later end up with them testing the
constant-folding version. That might not be a bad outcome, although a
regression-testing opportunity is lost once constant folding is added.

* `valid/implicit_casts/static_initializers.c`: suggest changing order
to match between check in `main()` and initializer (move 'i2' test
down)

* `valid/unsigned_expressions.c`: tiny typo 'sign_extending'

(reached end of ch12)

**Comment by nlsandler** [comment]
Chapter 19 tests now ready for review! Going to address your feedback on chapters 11/12 before moving on to chapter 20.

**Comment by nlsandler** [comment]
I've addressed (or filed issues to address) most of your suggestions. I agree with your usual naming comment - I'll update in later chapters too.

I have follow-up questions about a couple points:
* In `chapter_11/valid/long_expressions/large_constants.c` you mentioned inverted return values but it looks like it's following the normal convention - do you remember what you were flagging here?

  One possible source of confusion: the convention for the whole program is to return 0 on success and nonzero on failure, while individual test functions do the reverse. This helps make the individual test functions shorter/more readable in isolation (since you can write `return result == expected`) but would it be clearer overall if they also returned 0 on success?

* Re: using some sort of macro expansion so we can write out values arithmetically. I'm guessing you mean writing e.g. `2^32 - 6` in place of `4294967290l`, is that right?

  I think readability is important but debuggability is more important - a reader will only look at a test case if it's failing. So I want to keep the code as close as possible to what their compiler will actually be processing, which makes it easier to figure out what assembly code corresponds to source-level constructs, figure out where to set breakpoints in the assembly code, etc. I think using some sort of macro expansion would undermine that enough to not be worth it.

  I do want to address the readability issue though. A simple fix is to comment the values of these big constants every time they appear, e.g. 

  ```c
      return (ui_a + 2147483653u /* 2^31 + 5 */ == 2147483663u /* 2^31 + 15 */);
  ```
  Do you think that would meaningfully help with readability or just clutter things further?

* Re: general comment on constant folding-preventing helper functions. I think there are a few reasons to keep them, aside from regression testing:
  1. Splitting up tests into smaller functions instead of having everything in main makes debugging easier.
  2. Better test coverage in the current chapter (e.g. making sure we correctly infer the types of both constants and variables)
  3. Functions that can't be totally constant folded gives us more test coverage for register allocation.
 
  But we can do this without the horrible pattern where we have one global variable we assign to over and over, by just using static local variables instead so each test case is self-contained (and perhaps having better comments). E.g. in `common_type.c`, instead of

  ```c
  int addition(void) {
      // l = 2147483653
      // i = 10
  
      /* The common type of i and l is long, so we should
       * promote i to a long, then perform addition.
       * If we instead converted l to an int, its value would be
       * -2147483643, and the result of i + l would be -2147483633
       */
      long result = i + l;
      return (result == 2147483663l);
  }
  ```
  we could have
  ```c
  int test_addition(void) {
  
      static long l = 2147483653l; // 2^31 + 5
      static int i = 10;
  
      // Common type is long; we should promote i to long, then add
      long result = i + l; // 10 + (2^31 + 5)
  
      /* Validate the result. */
      return (result == 2147483663l /* 2^31 + 15 */);
  
      /* If instead we converted l to an int,
       * its value would be -2147483643 (i.e. -2^31 + 5),
       * and the result of i + l would be -2147483633 (i.e. -2^31 + 15)
       */
  }
  ```
   
  And in main we'd just call `test_addition()` `test_subtraction()` and so on without updating variables or performing any other operations. Does that seem like a reasonable plan?
  (Of course we do need to test the constant-folding implementation too, but the chapter 19 tests cover that)

**Pull request merged**
